/**
 * Fumadocs source loader.
 *
 * NOTE: `@/.source` is auto-generated by fumadocs-mdx during `next build`.
 * It will not exist on a fresh clone until you run `next build` or `next dev`.
 *
 * Import pattern mirrors the official fumadocs-ui example for Next.js.
 */

import { docs } from "@/.source/server";
import { loader } from "fumadocs-core/source";

export const source = loader({
  baseUrl: "/docs",
  source: docs.toFumadocsSource(),
});
